name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dimkr/locwm/ci-container:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ci.sh
        run: ./ci.sh